on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: Docs Test
jobs:
  test:
    name: test docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - name: "Test"
        run: |
          cd docs
          bun install 
          bun test
  build:
    name: build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - name: "Build"
        run: |
          cd docs
          bun install
          bun run build
